title: RSC Solutions Homepage
description: RSC Solutions Systems Integrations | Rural Onshore | Custom Application Development | Project Management | Cloud Solutions | SOW | Global Industrialization
theme: jekyll-theme-slate

seo:
	title: RSC Solutions Premiere Recruiting
	description: Candidate acquisition center for direct placement and IT Solutions
	url: https://rscsolutions.com
	author: RSC Dev Team
	twitter: 
		username: RSCInc
		card: summary